# Generated by Django 4.2.4 on 2023-08-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassengerId', models.PositiveBigIntegerField(unique=True)),
                ('Survived', models.BooleanField()),
                ('Pclass', models.SmallIntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=15)),
                ('Age', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('SibSp', models.IntegerField()),
                ('Parch', models.IntegerField()),
                ('Ticket', models.CharField(max_length=20)),
                ('Fare', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Cabin', models.CharField(blank=True, max_length=20, null=True)),
                ('Embarked', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
    ]
